### PR TITLE
change to use the compiler plugin instead

### PR DESCRIPTION
**Pull request by kailuowang**

### CODE REVIEW

**Comment by milessabin** [comment]
Happy to merge, but why delete `src/main/scala/si2712fix/demo3.scala`?

**Comment by kailuowang** [comment]
oops, didn't even think when I saw it fails compilation, just jumped into the conclusion that the annotation isn't supported by the plugin... typical me. will fix soon.

**Comment by milessabin** [comment]
There's a library jar which contains the annotation ... projects will have to add that as a library dependency.

**Comment by kailuowang** [comment]
fixed. sorry about that.

**Comment by milessabin** [comment]
Fantastic! Thanks :-)

**Pull request merged**
